insert into category (name) values ('Arts');
insert into category (name) values ('Automotive');
insert into category (name) values ('Baby');
insert into category (name) values ('Beauty');
insert into category (name) values ('Books');
insert into category (name) values ('Computers');
insert into category (name) values ('Electronics');
insert into category (name) values ('Women''s Fashion');
insert into category (name) values ('Men''s Fashion');
insert into category (name) values ('Girls'' Fashion');
insert into category (name) values ('Boys'' Fashion');
insert into category (name) values ('Health');
insert into category (name) values ('Home');
insert into category (name) values ('Industrial');
insert into category (name) values ('Luggage');
insert into category (name) values ('Movies');
insert into category (name) values ('Music');
insert into category (name) values ('Pet Supplies');
insert into category (name) values ('Software');
insert into category (name) values ('Sports');
insert into category (name) values ('Tools');
insert into category (name) values ('Toys');
insert into category (name) values ('Games');